name: Cypress tests tesults
on: 
  workflow_dispatch: 

jobs:
  cyress-electron-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.14.0-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1 
      options: --user 1001

    steps: 
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: node runner-electron.js
      
    env: 
      TOKEN_ELECTRON: ${{ secrets.TOKEN_ELECTRON}}


  cyress-chrome-tests:
    needs: cyress-electron-tests
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.14.0-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1 
      options: --user 1001

    steps: 
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: node runner-chrome.js

    env: 
      TOKEN_CHROME: ${{ secrets.TOKEN_CHROME}}
  
  cyress-firefox-tests:
    needs: cyress-electron-tests
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.14.0-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1 
      options: --user 1001

    steps: 
      - name: Get Code
        uses: actions/checkout@v4
    
      - name: Install dependencies
        run: yarn install
    
      - name: Run E2E tests
        run: node runner-firefox.js
    env: 
      TOKEN_FIREFOX: ${{ secrets.TOKEN_FIREFOX}}