name: Cypress tests tesults
on: 
  workflow_dispatch: 
    inputs: 
      cli:
        description: Run by cypress node command
        default: node runner.js 

jobs:
  cyress-electron-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.14.0-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1 
      options: --user 1001

    steps: 
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}